In [1]:
import numpy as np
import pandas as pd 
from sklearn.model_selection import train_test_split
import tensorflow as tf
import  pandas as pd 

from tensorflow import  keras
from keras.layers import Input, Embedding, Dot, Flatten
from keras.models import Model


2023-10-06 10:55:28.494812: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-10-06 10:55:28.884387: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-10-06 10:55:28.884446: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-10-06 10:55:28.886305: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-10-06 10:55:29.067690: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-10-06 10:55:29.069760: I tensorflow/core/platform/cpu_feature_guard.cc:182] This Tens

In [9]:
# Sample movie ratings data (user_id, movie_id, rating)
#Using embeddings to capture user and movie interactions and predicts ratings based on these embeddings
data = np.array([
    [1, 1, 5],
    [1, 2, 4],
    [2, 1, 3],
    [2, 2, 2],
    [3, 2, 5],
    [3, 3, 4],
    [4, 3, 5],
    [4, 4, 4],
])
dataFrame = pd.DataFrame(data)

print(data)

unique_users, unique_movies = len(np.unique(data[:, 0])), len(np.unique(data[:, 1]))

EMBEDDING_SIZE = 50

user_input = Input(shape=(1,))
user_embedding = Embedding(unique_users, EMBEDDING_SIZE)(user_input)
user_embedding_flattened = Flatten()(user_embedding)

movie_input = Input(shape=(1,))
movie_embedding = Embedding(unique_movies, EMBEDDING_SIZE)(movie_input)
movie_embedding_flattened = Flatten()(movie_embedding)

dot_product_layer = Dot(axes=1)([user_embedding_flattened, movie_embedding_flattened])

#creating  and compiling hte  model .

model = Model(inputs=[user_input, movie_input], outputs=dot_product_layer)
model.compile(loss='mean_squared_error', optimizer='adam')

user_ids = data[:, 0]
movie_ids = data[:, 1]
ratings = data[:, 2]

model.fit([user_ids, movie_ids], ratings, epochs=100, verbose=1)


user_id_to_predict = 1
movies_to_predict = np.array([3, 4]) 


#note that while training the model , we are passing a 2D aray/table like data above .

user_id_duplicated = np.array([user_id_to_predict] * len(movies_to_predict))

predicted_ratings = model.predict([user_id_duplicated, movies_to_predict])

# Print the predicted ratings
for i, movie_id in enumerate(movies_to_predict):
    print(f"Predicted rating for movie {movie_id}: {predicted_ratings[i][0]}")
    
    
    dataFrame




[[1 1 5]
 [1 2 4]
 [2 1 3]
 [2 2 2]
 [3 2 5]
 [3 3 4]
 [4 3 5]
 [4 4 4]]
Epoch 1/100


InvalidArgumentError: Graph execution error:

Detected at node model_1/embedding_2/embedding_lookup defined at (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main

  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/ipykernel_launcher.py", line 17, in <module>

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/traitlets/config/application.py", line 1053, in launch_instance

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 736, in start

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 195, in start

  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever

  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once

  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 516, in dispatch_queue

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 505, in process_one

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 412, in dispatch_shell

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 740, in execute_request

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 422, in do_execute

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 546, in run_cell

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3024, in run_cell

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3079, in _run_cell

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3284, in run_cell_async

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3466, in run_ast_nodes

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3526, in run_code

  File "/tmp/ipykernel_7223/572398293.py", line 40, in <module>

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/keras/src/engine/training.py", line 1783, in fit

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/keras/src/engine/training.py", line 1377, in train_function

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/keras/src/engine/training.py", line 1360, in step_function

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/keras/src/engine/training.py", line 1349, in run_step

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/keras/src/engine/training.py", line 1126, in train_step

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/keras/src/engine/training.py", line 589, in __call__

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/keras/src/engine/base_layer.py", line 1149, in __call__

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 96, in error_handler

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/keras/src/engine/functional.py", line 515, in call

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/keras/src/engine/functional.py", line 672, in _run_internal_graph

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/keras/src/engine/base_layer.py", line 1149, in __call__

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 96, in error_handler

  File "/home/kering/Desktop/MachineLearningProjects/KnowledgeBasedSystemsML/KnowledgeBasedSystemsVenv/lib/python3.10/site-packages/keras/src/layers/core/embedding.py", line 272, in call

indices[0,0] = 4 is not in [0, 4)
	 [[{{node model_1/embedding_2/embedding_lookup}}]] [Op:__inference_train_function_1501]

In [7]:
from sklearn import  metrics

data = [[80, 951, 75, 171],
        [82, 1110, 68, 175], 
        [70, 1200, 76, 168],
        [69, 1400, 72, 170],
        [70, 1000, 80, 160], 
        [65, 1800, 72, 150],
        [80, 1220, 68, 140], 
        [62, 1121, 71, 139]
        ]
comments = ['good','good','good','good','bad', 'bad', 'good','bad']
jacinta = [70, 820, 65, 149]
accuracies = []
for d in data:
    a = metrics.accuracy_score(np.array(d),np.array(jacinta))
    accuracies.append(a)

print(accuracies)

d_dif = []
for d in data:
    total = 0
    for i in range(len(d)):
        sq = jacinta[i] - d[i]
        total = total + (sq*sq)
    d_dif.append(sum)
    
def min_f(arr):
    m = arr[0]
    for i in arr:
        if i < m:
            m = i
    return m

print(d_dif)
min = min_f(d_dif)
print(min)
print(comments[d_dif.index(min)])

[0.0, 0.0, 0.25, 0.0, 0.25, 0.0, 0.0, 0.0]
[90801, 90801, 90801, 90801, 90801, 90801, 90801, 90801]
90801
good


In [12]:

# True labels and predicted labels from your model
true_labels = [0, 1, 1, 0, 1, 0, 0, 1]
predicted_labels = [0, 1, 0, 1, 1, 0, 1, 1]



# Calculate the performance metrics precision, recall, and F1-score
accuracy = metrics.accuracy_score(true_labels, predicted_labels)
precision = metrics.precision_score(true_labels, predicted_labels)
recall = metrics.recall_score(true_labels, predicted_labels)
f1_score = metrics.f1_score(true_labels, predicted_labels)

print(f"Accuracy: {accuracy}")

print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1-Score: {f1_score}")

# Compute the confusion matrix
confusion_matrix = metrics.confusion_matrix(true_labels, predicted_labels)
print("Confusion Matrix:")
confusion_matrix


Accuracy: 0.625
Precision: 0.6
Recall: 0.75
F1-Score: 0.6666666666666665
Confusion Matrix:


array([[2, 2],
       [1, 3]])

In [22]:
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics, datasets

nb= GaussianNB()
iris = datasets.load_iris()

(iris_train_ftrs, iris_test_ftrs,
iris_train_tgt, iris_test_tgt) = train_test_split(iris.data,
iris.target,
test_size=.25)

fit= nb.fit(iris_train_ftrs, iris_train_tgt)
preds = fit.predict(iris_test_ftrs)
print("NB accuracy:",
metrics.accuracy_score(iris_test_tgt, preds))



NB accuracy: 1.0


This is the  meaning of programming  man 


In [60]:
 
data =[
    
    ["Yes", "Yes", "No", "Yes", "Yes", "No", "No", "No", "No", "Yes", "No", "Yes"],
    ["No", "No", "Yes", "No", "No", "Yes", "Yes", "No", "Yes", "Yes", "No", "Yes"],
    ["No", "No", "No", "Yes", "Yes", "No", "No", "No", "Yes", "Yes", "No", "Yes"],
    ["Yes", "Yes", "No", "Yes", "No", "Yes", "No", "Yes", "No", "Yes", "No", "Yes"],
    [ "Some", "Full", "Some", "Full", "Full", "Some","None", "Some", "Full", "Full", "None", "Full"],
    ["$$$","$", "$","$", "$$$","$$", "$","$$","$","$$$","$","$$$"],
    [ "No", "No", "No", "Yes", "No", "Yes","Yes", "Yes", "Yes", "No", "No", "No"],
    [ "Yes", "No", "No", "No", "Yes", "Yes","No", "Yes", "No", "Yes", "No", "No"],
    [ "French", "Thai", "Burger", "Thai", "French", "Italian", "Burger", "Thai", "Burger", "Italian", "Thai", "Burger"],
    ["0–10", "30–60", "0–10", "10–30", ">60", "0–10","0–10", "0–10", ">60", "10–30", "0–10", "30–60"]
]


classes = ['Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'Yes']
col_labels= ['Alternate', 'Bar', 'Friday', 'Hungry', 'Patron', 'Price', 'Raining', 'Reservation', 'Type', 'Estimated_Time']

col_dict = {i: label for i, label in enumerate(col_labels)}

dataFrame = pd.DataFrame(data).transpose()
df=dataFrame.copy()
print(col_dict)

df.columns=col_labels
df

{0: 'Alternate', 1: 'Bar', 2: 'Friday', 3: 'Hungry', 4: 'Patron', 5: 'Price', 6: 'Raining', 7: 'Reservation', 8: 'Type', 9: 'Estimated_Time'}


Alternate  Bar Friday Hungry Patron Price Raining Reservation     Type  \
0        Yes   No     No    Yes   Some   $$$      No         Yes   French   
1        Yes   No     No    Yes   Full     $      No          No     Thai   
2         No  Yes     No     No   Some     $      No          No   Burger   
3        Yes   No    Yes    Yes   Full     $     Yes          No     Thai   
4        Yes   No    Yes     No   Full   $$$      No         Yes   French   
5         No  Yes     No    Yes   Some    $$     Yes         Yes  Italian   
6         No  Yes     No     No   None     $     Yes          No   Burger   
7         No   No     No    Yes   Some    $$     Yes         Yes     Thai   
8         No  Yes    Yes     No   Full     $     Yes          No   Burger   
9        Yes  Yes    Yes    Yes   Full   $$$      No         Yes  Italian   
10        No   No     No     No   None     $      No          No     Thai   
11       Yes  Yes    Yes    Yes   Full   $$$      No          No   Burger   

   Estimated_Time  
0            0–10  
1           30–60  
2            0–10  
3           10–30  
4             >60  
5            0–10  
6            0–10  
7            0–10  
8             >60  
9           10–30  
10           0–10  
11          30–60

In [61]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
import numpy as np
import pandas as pd
from sklearn.base import BaseEstimator, TransformerMixin
print("This is the  meaning of programming  man ")


class FeatureEncoder(BaseEstimator, TransformerMixin):
    def __init__(self, dict_values):
        self.dict_values= dict_values
        
    def fit(self, x, y=None):
        return self

    def transform(self, data_frame):  
        dictionary_values = self.dict_values
        for key in dictionary_values:
            data_frame[key] = data_frame[key].replace(
                dictionary_values[key]
            )
            
        return data_frame
    
    
Yes_No_Dict={
    "Yes":1,
    "No":0
}
def generate_column_dict():
    return {"Yes": 1, "No": 0}

val_dict = {
    "Alternate": generate_column_dict(),
    "Bar": generate_column_dict(),
    "Friday": generate_column_dict(),
    "Hungry": generate_column_dict(),
    "Price": {
        "$":100,
        "$$":200,
        "$$$":300,
        
    },
    "Raining": generate_column_dict(),
    "Reservation": generate_column_dict(),
    "Type": generate_column_dict(),
    
    "Estimated_Time": {
        "0-10":"Short",
        "10-30":"Medium",
        ">60":"Long"
    }
}
featureEncoder = FeatureEncoder(dict_values=val_dict);
featureEncoder.fit_transform(df)



This is the  meaning of programming  man 


Alternate  Bar  Friday  Hungry Patron  Price  Raining  Reservation  \
0           1    0       0       1   Some    300        0            1   
1           1    0       0       1   Full    100        0            0   
2           0    1       0       0   Some    100        0            0   
3           1    0       1       1   Full    100        1            0   
4           1    0       1       0   Full    300        0            1   
5           0    1       0       1   Some    200        1            1   
6           0    1       0       0   None    100        1            0   
7           0    0       0       1   Some    200        1            1   
8           0    1       1       0   Full    100        1            0   
9           1    1       1       1   Full    300        0            1   
10          0    0       0       0   None    100        0            0   
11          1    1       1       1   Full    300        0            0   

       Type Estimated_Time  
0    French           0–10  
1      Thai          30–60  
2    Burger           0–10  
3      Thai          10–30  
4    French           Long  
5   Italian           0–10  
6    Burger           0–10  
7      Thai           0–10  
8    Burger           Long  
9   Italian          10–30  
10     Thai           0–10  
11   Burger          30–60

In [59]:
my_dict = {
    "name": "John",
    "age": 30,
    "city": "New York"
}

for key in my_dict:
    print(key)

name
age
city
